name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: LoginApp Unit Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: postgres
          POSTGRES_DB: software-testing
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
        ports:
          - '5432:5432'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: PostgreSQL JDBC and JUnit Driver
        run: |
          export DISPLAY=:99
          sudo Xvfb :99 -screen 0 1280x1024x24 &
          sleep 5
          mkdir -p libs
          curl -O https://jdbc.postgresql.org/download/postgresql-42.7.4.jar
          mv postgresql-42.7.4.jar libs/
          curl -O https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.0/junit-platform-console-standalone-1.9.0.jar
          mv junit-platform-console-standalone-1.9.0.jar libs/
          
      - name: Wait for PostgreSQL to be ready and create tables
        run: |
          PGPASSWORD=pass psql -h localhost -U postgres -d software-testing -c "
          CREATE TABLE IF NOT EXISTS \"User\" (
              userId SERIAL PRIMARY KEY,
              Name VARCHAR(100) NOT NULL,
              Email VARCHAR(100) NOT NULL UNIQUE,
              Password VARCHAR(255) NOT NULL
          );
          INSERT INTO \"User\" (Name, Email, Password)
          VALUES 
              ('John Doe', 'johndoe@example.com', 'password123'),
              ('Jane Smith', 'janesmith@example.com', 'password456'),
              ('Mike Johnson', 'mikejohnson@example.com', 'password789'),
              ('Alice Brown', 'alicebrown@example.com', 'password101'),
              ('Tom Clark', 'tomclark@example.com', 'password202');
          "

      - name: Compile Java code
        run: javac -cp "libs/*" -d out src/LoginApp.java test/LoginAppTest.java

      - name: Run LoginAppTest
        run: |
          export DISPLAY=:99
          java -cp "libs/*:out" org.junit.platform.console.ConsoleLauncher --class-path out --select-class LoginAppTest